// app/head.tsx
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Head() {
  return (
    <>
      <meta name="description" content="Generated by create next app" />
    </>
  );
}
