import type { Metadata } from "next";
import { Pixelify_Sans, Manrope } from "next/font/google";
import "./globals.css";
import ReactLenis from "lenis/react";
import AnimatedCursor from "react-animated-cursor";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

const pixelifySans = Pixelify_Sans({
  variable: "--font-pixelify-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pixelifySans.variable} ${manrope.variable} antialiased`}
      >
        {/* Custom Cursor - Hidden on smaller screens */}
        <div className="hidden lg:block">
          <AnimatedCursor
            innerSize={8}
            outerSize={35}
            color="139, 69, 19" // RGB for SaddleBrown
            outerAlpha={0.3}
            innerScale={1}
            outerScale={2.5}
            clickables={["a", "button", ".hoverable"]}
          />
        </div>
        <ReactLenis root>{children}</ReactLenis>
      </body>
    </html>
  );
}
